# Site settings
baseURL = "/"
languageCode = "en-us"
title = "Forty"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Rebecca Hoffmann"
  description = "Comercio Exterior en América Latina"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Comercio América Latina"
    subtitle = "By Rebecca Hoffmann"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Blogs"
      url = "blogs"

    [[params.navigation.links]]
      name = "Generic Blog"
      url = "blogs/ipsum"

    [[params.navigation.links]]
      name = "Elements"
      url = "elements.html"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "Get Started"
      url = "blogs"

    # Button Style 2
    [[params.navigation.button2]]
      name = "Log In"
      url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Comercio Exterior en América Latina"
    subtitle = "PROYECTO FINAL UTILIZANDO OPEN TRADE STATISTICS"
    buttonText = "¿EMPEZAMOS?"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Introducción al proyecto"
      subtitle = "Armando la página y limpiando los datos"
      image = "pic01.jpg"
      url = "blogs/2020-12-06-introduccion"

    [[params.tiles.showcase]]
      title = "Datos Historicos del Comercio Exterior"
      subtitle = "El desarrollo histórico del comercio exterior en América Latina"
      image = "pic02.jpg"
      url = "blogs/historico"

    [[params.tiles.showcase]]
      title = "¿Qué país importa más?"
      subtitle = "Analisis de qué país importa más en América Latina"
      image = "pic03.jpg"
      url = "blogs/exportacion"

    [[params.tiles.showcase]]
      title = "¿Qué productos se exporta?"
      subtitle = "Analisis del tipo de productos que se exportan en América Latina"
      image = "pic04.jpg"
      url = "blogs/ipsum"

    [[params.tiles.showcase]]
      title = "Exportación en Argentina"
      subtitle = "Analisis de las exportaciones en Argentina"
      image = "pic05.jpg"
      url = "blogs/ipsum"

    [[params.tiles.showcase]]
      title = "¿A quién se exporta Argentina?"
      subtitle = "Analisis de los socios comerciales principales de Argentina"
      image = "pic06.jpg"
      url = "blogs/ipsum"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "¿Dónde tiene América Latina su fuerza comercial?"
    subtitle = """ 
    Scholars and practictioners alike have been debating how to drive growth to Latin America. 
    The economic models of the ISI didn't bring suitanable growth to the region.
    Nor did the neoliberal models of the 1990s.
    Some scholars have argued that there is a need for heavy investment in education and skills to break out of the middle income-trap that most Latin American countries are in.
    But before coming up with solutions, we need to understand where the comercial strengths of Latin America lies.
    The aim of this project is to explore some of the comercial dynamics of Latin America."""
    buttonText = "Mira todos los articulos del proyecto"
    url = "blogs"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "hola@becci.dk"


    [[params.contact.address]]
    title = "Address"
    street = "Bulnes"
    city = "Buenos Aires"
    country = "Argentina"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Rebecca Hoffmann"

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://www.twitter.com/becciabroad"
      label = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com/becciabroad"
      label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com/becciabroad"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/rehoffmann"
      label = "LinkedIn"
